GroupCoursework/Controllers/ActorsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroupCoursework.Models;

namespace GroupCoursework.Controllers
{
    public class ActorsController : Controller
    {
        private readonly DatabaseContext _context;

        public ActorsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ActorNumber == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActorNumber,ActorFirstName,ActorSurname")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ActorNumber,ActorFirstName,ActorSurname")] Actor actor)
        {
            if (id != actor.ActorNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ActorNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ActorNumber == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actors.FindAsync(id);
            _context.Actors.Remove(actor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actors.Any(e => e.ActorNumber == id);
        }
    }
}

GroupCoursework/Controllers/AssistantController.cs
using GroupCoursework.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GroupCoursework.Controllers
{
    [Authorize(Roles ="Admin,Staff")]
    public class AssistantController : Controller
    {
        private readonly DatabaseContext _dbcontext;

        public AssistantController(DatabaseContext dbcontext)
        {
            _dbcontext = dbcontext;
        }
        public IActionResult Index()
        {
            return View();
        }

        //Function 3
        public IActionResult GetDateOut(int memberNumber)
        {
            /**
select distinct DT.DVDTitleName,DC.CopyNumber,L.DateOut,DATEDIFF(DAY,L.DateOut,'2022-04-14') aS dIFF from DVDTitles dt
inner join DVDCopys dc 
on dt.DVDNumber = dc.DVDNumber
inner join Loans l
on dc.CopyNumber = l.CopyNumber
inner join CastMembers c
on c.DVDNumber = dc.DVDNumber
inner join Members m
on l.MemberNumber = m.MembershipNumber
where (L.DateOut >= (GETDATE()-31) and m.MembershipNumber = 3);

             DateTime currentDate = DateTime.Now.Date;
            */

            DateTime currentDate = DateTime.Now.Date;
            DateTime lastDate = currentDate.Subtract(new TimeSpan(31, 0, 0, 0, 0));

            var dvdTitle = _dbcontext.DVDTitles.ToList();
            var dvdCopy = _dbcontext.DVDCopys.ToList();
            var castMember = _dbcontext.CastMembers.ToList();
            var member = _dbcontext.Members.ToList();
            var loan = _dbcontext.Loans.ToList();


            var details = from d in dvdTitle
                          join dc in dvdCopy
                          on d.DVDNumber equals dc.DVDNumber into table1
                          from dc in table1.ToList().Distinct().Where(dc => dc.DVDNumber == d.DVDNumber)
                          join l in loan on dc.CopyNumber equals l.CopyNumber into table2
                          from l in table2.ToList().Distinct().Where(l => l.CopyNumber == dc.CopyNumber)
                          join c in castMember
                          on dc.DVDNumber equals c.DVDNumber into table3
                          from c in table3.ToList().Distinct().Where(c => c.DVDNumber == dc.DVDNumber)
                          join m in member
                          on l.MemberNumber equals m.MembershipNumber into table4
                          from m in table4.ToList().Distinct().Where(m => m.MembershipNumber == l.MemberNumber && m.MembershipNumber == memberNumber && DateTime.Parse(l.DateOut) >= lastDate)
                          select new { dvdTitle = d, castMember = c, dvdCopy = dc, loan = l, member = m };

            //var r = _context.Actors.FirstOrDefault();
            //ViewBag.last = r;
            ViewBag.date = details;
            ViewBag.memberNumbers = _dbcontext.Members.ToArray();
            return View();
        }
        //FUNCTION 4
        public IActionResult GetList()
        {
            /**
        select dt.DVDTitleName,dt.DateReleased,p.ProducerName,s.StudioName,c.CastMemberNo,a.ActorFirstName,a.ActorSurname
            from DVDTitles dt
inner join CastMembers c on c.DVDNumber = dt.DVDNumber
inner join Producers p on p.ProducerNumber = dt.ProducerNumber
inner join Studios s on s.StudioNumber = dt.StudioNumber
inner join Actors a on a.ActorNumber = c.ActorNumber
order by  dt.DateReleased asc,a.ActorSurname asc
            */
            var dvdTitle = _dbcontext.DVDTitles.ToList();
            var producer = _dbcontext.Producers.ToList();
            var castMember = _dbcontext.CastMembers.ToList();
            var studio = _dbcontext.Studios.ToList();
            var actor = _dbcontext.Actors.ToList();
            var listProducer = from dt in dvdTitle
                               join c in castMember on dt.DVDNumber equals c.DVDNumber into table1
                               from c in table1.ToList().Where(c => c.DVDNumber == dt.DVDNumber).ToList()

                               join p in producer on dt.ProducerNumber equals p.ProducerNumber into table2
                               from p in table2.ToList().Where(p => p.ProducerNumber == dt.ProducerNumber).ToList()

                               join s in studio on dt.StudioNumber equals s.StudioNumber into table3
                               from s in table3.ToList().Where(s => s.StudioNumber == dt.StudioNumber).ToList()

                               join a in actor on c.ActorNumber equals a.ActorNumber into table4
                               from a in table4.ToList().Where(a => a.ActorNumber == c.ActorNumber).ToList()
                               orderby dt.DateReleased ascending, a.ActorSurname ascending
                               select new { dvdTitle = dt, castMember = c, actorDetails = a, studio = s, producer = p };
            //var r = _context.Actors.FirstOrDefault();
            //ViewBag.last = r;
            ViewBag.listProducer = listProducer;

            return View();
        }

        //last loan data not coming
        //FUNCTION 5
        //https://localhost:7135/Assistant/GetLoanDetails?copynumber=4
        public IActionResult GetLoanDetails(int copynumber)
        {
            /**
                   select dc.CopyNumber,m.MembershipFirstName,dt.DVDTitleName,l.DateOut,l.DateDue,l.DateReturned from Members m
            inner join loans l on l.MemberNumber= m.MembershipNumber
            inner join DVDCopys dc on dc.CopyNumber = l.CopyNumber
            inner join DVDTitles dt on dt.DVDNumber = dc.DVDNumber
            where l.CopyNumber = 2
            */
            var dvdTitle = _dbcontext.DVDTitles.ToList();
            var loan = _dbcontext.Loans.ToList();
            var lastloan = loan.LastOrDefault();
            var member = _dbcontext.Members.ToList();
            var dvdCopy = _dbcontext.DVDCopys.ToList();
            var loanDetails = (from l in loan
                               join m in member on l.MemberNumber equals m.MembershipNumber into table1
                               from m in table1.ToList().Where(m => m.MembershipNumber == l.MemberNumber).ToList()

                               join dc in dvdCopy on l.CopyNumber equals dc.CopyNumber into table2
                               from dc in table2.ToList().Where(dc => dc.CopyNumber == l.CopyNumber && l.CopyNumber == copynumber).ToList()

                               join dt in dvdTitle on dc.DVDNumber equals dt.DVDNumber into table3
                               from dt in table3.ToList().Where(dt => dt.DVDNumber == dc.DVDNumber).ToList()
                               group new { dt, l, m, dc } by new { l.CopyNumber, dt.DvdTitle, m.MembershipFirstName, m.MembershipLastName, m.MemberDOB, m.MembershipAddress, l.DateDue, l.DateOut, l.DateReturned }
                              into grp
                               select new
                               {
                                   grp.Key.CopyNumber,
                                   grp.Key.DvdTitle,
                                   grp.Key.MembershipFirstName,
                                   grp.Key.MembershipLastName,
                                   grp.Key.MemberDOB,
                                   grp.Key.MembershipAddress,
                                   grp.Key.DateDue,
                                   grp.Key.DateOut,
                                   grp.Key.DateReturned,
                               });
            //var r = _context.Actors.FirstOrDefault();
            //ViewBag.last = r;
            ViewBag.loanDetails = loanDetails;
            ViewBag.copyNumber = _dbcontext.DVDCopys.ToArray();
            return View();
        }


        //Function 6 
        public IActionResult AddDVDCopy() {
            var dvdcopy = _dbcontext.DVDCopys.ToList();
            var dvdtitle = _dbcontext.DVDTitles.ToList();

            var members = _dbcontext.Members.ToList();
            
            var loanType = _dbcontext.LoanTypes.ToList();

            ViewBag.member = members;
            ViewBag.loanType = loanType;

            var dvd = from dc in dvdcopy
                      join dt in dvdtitle on dc.DVDNumber equals dt.DVDNumber
                       select new { 
                       dvdtitle = dt,
                       dvdcopy = dc,
                       };
            ViewBag.dvd = dvd;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDVDCopy(Loan Loan, int member, int loantype, int copynumber)
        {
            var dvdcopy = _dbcontext.DVDCopys.ToList();
            var dvdtitle = _dbcontext.DVDTitles.ToList();

            var members = _dbcontext.Members.ToList();

            var loanType = _dbcontext.LoanTypes.ToList();

            ViewBag.member = members;
            ViewBag.loanType = loanType;

            var dvdcd = from dc in dvdcopy
                      join dt in dvdtitle on dc.DVDNumber equals dt.DVDNumber
                      select new
                      {
                          dvdtitle = dt,
                          dvdcopy = dc,
                      };
            ViewBag.dvd = dvdcd;


            var memberInfo = _dbcontext.Members.Where(x => x.MembershipNumber == member).First();
            String dob = memberInfo.MemberDOB;//GETTING MEMBER DOB
            String todaysDate = DateTime.Now.ToShortDateString();

            var today = DateTime.Now.ToShortDateString();


            //CONVERTING IN DATE TIME
            DateTime cDOB = DateTime.Parse(dob);
            DateTime ctodaysDate = DateTime.Parse(todaysDate);

            TimeSpan dayDiff = ctodaysDate.Subtract(cDOB);
            Console.Write(dayDiff.Days.ToString());
            var age = dayDiff.Days / 365;
            Console.Write(age);

            

            var dvd = _dbcontext.DVDTitles.ToList();
            var catogory = _dbcontext.DVDCategorys.ToList();
            // var dvdCopy = _dbcontext.DVDCopys.ToList();

GroupCoursework/Controllers/UserController.cs
using GroupCoursework.Models;
using Microsoft.AspNetCore.Mvc;

namespace GroupCoursework.Controllers
{
    public class UserController : Controller
    {
        private readonly DatabaseContext _context;

        public UserController(DatabaseContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        // https://localhost:7135/User/GetActorDetails?name=Holland
        // GET: NormalUserController/Details/5
        //FUNCTION 1
        public IActionResult GetActorDetails(String name)
        {

            var dvdTitle = _context.DVDTitles.ToList();
            var castMember = _context.CastMembers.ToList();
            var actorDetails = _context.Actors.ToList();
            var details =
                from d in dvdTitle
                join c in castMember
                on d.DVDNumber equals c.DVDNumber into table1
                from c in table1.Distinct().ToList().Where(c => c.DVDNumber == d.DVDNumber)
                join a in actorDetails on c.ActorNumber equals a.ActorNumber into table2
                from a in table2.Distinct().ToList().Where(a => a.ActorNumber == c.ActorNumber && a.ActorSurname == name)
                select new { dvdTitle = d, castMember = c, actorDetails = a };
            var r = _context.Actors.FirstOrDefault();
            ViewBag.last = r;
            ViewBag.name = details;
            ViewBag.Actors = actorDetails;
            return View();
        }

        //Function 2
        public IActionResult GetActorCopy(int actorID)
        {
            /**
         select dt.DVDTitleName,(dc.Stock - Count(*)) as "Dif(Stock Left)" from  loans l
        inner join DVDCopys dc
        on dc.CopyNumber = l.CopyNumber
        inner join DVDTitles dt
        on dt.DVDNumber = dc.DVDNumber
        group by l.CopyNumber, dc.Stock,dt.DVDTitleName
         * */
            ViewBag.actorName = _context.Actors.ToArray();
            String n = "0";
            var dvdTitle = _context.DVDTitles.ToList();
            var dvdCopy = _context.DVDCopys.ToList();
            var castMember = _context.CastMembers.ToList();
            var actorDetails = _context.Actors.ToList();
            var loan = _context.Loans.ToList();
            var details =
                (from l in loan
                 join dc in dvdCopy on l.CopyNumber equals dc.CopyNumber
                 join dt in dvdTitle on dc.DVDNumber equals dt.DVDNumber
                 join c in castMember on dt.DVDNumber equals c.DVDNumber
                 group new { l, dc, dt, c } by new { l.CopyNumber, dc.Stock, dt.DvdTitle, c.ActorNumber }
                          into grp
                 select new
                 {
                     DVDTitleName = grp.Key.DvdTitle,
                     Stock = grp.Key.Stock,
                     CastActorNumber = grp.Key.ActorNumber,
                     LoanCount = grp.Count(),
                 }).Where(x => x.CastActorNumber == actorID);
            ViewBag.name = details;
            return View(details);
        }


    }
}

GroupCoursework/Views/Assistant/GetDVDCopyListNotLoaned.cshtml
@{
    ViewData["Title"] = "GetDVDCopyListNotLoaned";
}

<style>
    body {
        background-image: url("../images/17.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover
    }
</style>
<body>
    <div class="container">
        <h1 style="color: white; text-align:center;">A list of all DVD copies currently on loan with total loans</h1>
        <div class="card" style="opacity:80%;">
            <table class="table">
                <thead>
                    <tr>

                        <th>DVDTitleName</th>
                        <th>CopyNumber</th>
                        <th>MembershipFirstName</th>
                        <th>DateOut</th>
                        <th>TotalLoans</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.totalloans)
                    {
                        <tr>
                            <td>@item.DvdTitle </td>
                            <td>@item.CopyNumber </td>
                            <td>@item.MembershipFirstName </td>
                            <td>@item.DateOut </td>
                            <td>@item.TotalLoans </td>
                            <td>
                                @*   <ul class="list-inline m-0">
                                    <li class="list-inline-item">
                                    <a href="@Url.Action("DeleteCopy","Assistant",new { item.dvdCopy.CopyNumber} )" class="btn btn-danger" type="button" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                                    </li>
                                    </ul>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

GroupCoursework/Views/Assistant/GetDVDofNoLoan.cshtml
@{
    ViewData["Title"] = "GetDVDofNoLoan";
}
<style>
body{
            background-image: url("../images/10.jpg");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover
}
</style>
<body>
    <div class="container">
    <h1 style="color: white; text-align:center;">GetDVDofNoLoan</h1>
    <div class="card" style="opacity:80%;">
    <table class="table">
        <thead>
            <tr>
                <th>DVD Title Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.dvd)
            {
                <tr>
                    <td>@item.dvdTitle.DvdTitle</td>
                </tr>
            }
        </tbody>
        </div>
    </table>
    </div>
</body>

GroupCoursework/Views/Assistant/GetDateOut.cshtml
@{
    ViewData["Title"] = "GetDateOut";
}
}
<style>
    body {
        background-image: url("../images/03.png");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover
    }
</style>
<body>
    <div class="container">
        <h1 style="color: white; text-align:center;">Details of DVD's copy</h1>


        <div class="container">
            <form action="@Url.Action("GetDateOut", "Assistant")" method="get">
                <div class="row">
                    <div class="col-sm">
                        <div class="form-group">
                            <label for="ActorSurName" class="control-label"></label>
                            <select id="memberNumber" name="memberNumber" class="form-control custom-select bg-white border-left-0 border-md" required>
                                <option value="">Select a member id</option>
                                @foreach (var member in ViewBag.memberNumbers)
                                {
                                    <option value="@member.MembershipNumber"> @member.MembershipNumber - @member.MembershipFirstName</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm">
                        <div class="form-group row">
                            <div class="col-sm-10 mt-4">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>


<div class="card" style="opacity:80%;">
        <table class="table">
            <thead>
                <tr>
                    <th>DVD Title Name</th>
                    <th>Copy Number</th>
                    <th>Date Out</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.date)
                {
                    <tr>
                        <td>@item.dvdTitle.DvdTitle</td>
                        <td>@item.dvdCopy.CopyNumber</td>
                        <td>@item.loan.DateOut</td>

                    </tr>
                }
            </tbody>
        </table>
        </div>
    </div>
</body>

GroupCoursework/Views/Assistant/GetListOfDVDCopy.cshtml
@{
    ViewData["Title"] = "GetListOfDVDCopy";
}
<style>
body{
            background-image: url("../images/3.jpg");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover
}
</style>
<body>
    <div class="container">
        <h1 style="color: white; text-align:center;">The list of DVD Copies purchased year ago and not on loan</h1>
        @if (ViewBag.copyDeleted)
        {
            @*    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>DVD Copy has been deleted!</strong>
                <button type="button" asp-action="GetListOfDVDCopy" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>*@
        }
        <div class="card" style="opacity:80%;">
            <table class="table">
                <thead>
                    <tr>

                        <th>Copy Number</th>
                        <th>Date Returned</th>
                        <th>Date Purchased</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.dvdList)
                    {
                        <tr>
                            <td>@item.dvdCopy.CopyNumber</td>
                            <td>@item.loan.DateReturned</td>
                            <td>@item.dvdCopy.DatePurchased</td>
                            <td>
                                <ul class="list-inline m-0">
                                    <li class="list-inline-item">
                                        <a href="@Url.Action("DeleteCopy","Assistant",new { item.dvdCopy.CopyNumber} )" class="btn btn-danger" type="button" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

GroupCoursework/Views/Assistant/Index.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> UserManager;

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center" style="color:white;font-weight:800">Index</h1>
<style>
    /*.container {
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
    }*/

    li{
        font-weight:700;
    }
</style>

<div class="container">
    <ul class="m-2" style="opacity:80%;">
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="User" asp-action="GetActorDetails">1. DVD's Stocked by the shop</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="User" asp-action="GetActorCopy">2. Check Copies</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetDateOut">3. Select member's' loaned DVDs within the 31 Days</a>
        </li>

        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetList">4. List of Producer, Studio and cast list of all the DVDs</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetLoanDetails">5. Last Loaned Detail</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="AddDVDCopy">6. Issue DVD copy to loan a member</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="ListAllLoans">7. Returned DVD copy report</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetTotalLoans">8. List of all members with their detail like loans</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="DVDTitle" asp-action="Create">9. Create new DVD title</a>
        </li>
           <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Producers" asp-action="Create">9. Create new Producer title</a>
        </li>
          <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Studios" asp-action="Create">9. Create new Studio title</a>
        </li>
          <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Actors" asp-action="Create">9. Create new Actor title</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetListOfDVDCopy">10. Delete Old DVDs</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetDVDCopyListNotLoaned">11. List of all DVD copies currently on loan </a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="MemberListNotBorrowed">12. Member who has not borrowed DVD for the past 31 days</a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Assistant" asp-action="GetDVDofNoLoan">
                13. List of all DVD titles in the shop where no copy of the
                title has been loaned in the last 31 days
            </a>
        </li>
        <li class="list-group m-1">
            <a class="list-group-item" asp-area="" style="color: black" asp-controller="Account" asp-action="ResetPassword">14. Password Change</a>
        </li>
        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
            <li class="list-group m-1">
                <a class="list-group-item" asp-area="" style="color: black" asp-controller="Account" asp-action="ListUsers">14. Reset Other User Password</a>
            </li>
              <li class="list-group m-1">
                <a class="list-group-item" asp-area="" style="color: black" asp-controller="Account" asp-action="RegisterStaff">Register Staff</a>
            </li>
        }



    </ul>
</div>
<br />

GroupCoursework/Views/Assistant/ListAllLoans.cshtml
@{
    ViewData["Title"] = "ListAllLoans";
}
<style>
body{
background-image:url("../images/3.jpg");
background-repeat:no-repeat;
background-size:cover;
}
th{
    color:white;
}
</style>
<body>
<h1 class="text-center" style="font-weight:800; color:white;">Details of DVD currently on loan</h1>
<div class="container">
<table class="table" style="color:white;">
    <thead>
        <tr style="color:white; background-color:#F2D8B3; height: 50px; text-align:center">
            <th>Copy Number</th>
            <th>Membership FirstName</th>
            <th>Date Due</th>
            <th>Date Returned</th>
             <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.loanDetails)
        {
            <tr style="text-align:center" >
                <td style="width:160px">@item.loan.CopyNumber </td>
                <td style="width:200px">@item.member.MembershipFirstName </td>
                <td style="width:160px">@item.loan.DateDue </td>
                <td style="width:160px; color:red">Not Returned </td>
                <td>
                    <ul class="list-inline m-0">
                        <li class="list-inline-item">
                            <a href="@Url.Action("EditDVDCopyDetails","Assistant",new { item.loan.LoanNumber} )" class="btn btn-primary" type="button" data-toggle="tooltip" data-placement="top" title="Update">Update Loan Records</a>
                        </li>
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</body>